interface IProject {
  id: string;
  imageUrl: string;
  name: string;
  text: string;
  editionalText?: string;
}

export const projects: IProject[] = [
  {
    id: '1',
    imageUrl: 'https://icapgroupgmbh.com/crm.png',
    name: 'Super Easy CRM',
    text: 'Super Easy CRM: Plattform zur Rationalisierung von Verkaufs- und Kundendienstprozessen.',
    editionalText: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id justo quis orci aliquam porttitor nec ac orci. Vivamus ligula dui, aliquam in auctor eu, pulvinar at risus. Nulla facilisi. Morbi vitae magna at lorem rutrum tincidunt. Quisque in tempor justo. Cras risus metus, vehicula sit amet malesuada eget, convallis at lorem. Quisque vel nulla scelerisque, semper elit ultricies, euismod enim. Maecenas iaculis, ipsum vitae volutpat fringilla, neque massa elementum justo, at ultricies augue nunc ut quam. Phasellus vitae sagittis purus, vel sodales justo. Aliquam purus urna, luctus vel interdum in, luctus at sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus et nulla massa. Cras sollicitudin semper nisl, quis lobortis velit eleifend vitae. Morbi eget eros metus. Donec in orci quis orci facilisis lobortis viverra eget neque. Curabitur aliquam risus sem, in fringilla massa rhoncus vitae. Donec ex mi, ornare a convallis eu, maximus vel neque. Phasellus odio lacus, consectetur eget arcu eget, mattis auctor mi. Aliquam lacinia diam urna, scelerisque cursus felis convallis non. Duis mattis, neque sed consequat dignissim, est orci cursus ex, a bibendum metus lacus sit amet elit. Ut ultricies condimentum lorem, non blandit massa tempor ac. Nam pharetra, turpis eget rhoncus aliquam, quam augue faucibus justo, sit amet iaculis elit nulla ut massa. Vivamus luctus velit ac ipsum eleifend malesuada. Cras sodales finibus massa, at dapibus sem dapibus ac. Praesent a feugiat elit, et venenatis metus. Etiam accumsan, nibh vitae convallis finibus, magna est auctor sem, ut fermentum turpis nisi rutrum enim. Phasellus posuere felis et est ultricies, sed venenatis arcu luctus. Nam eu odio libero. In imperdiet eleifend nulla, ut tristique leo hendrerit ut. Pellentesque vel ex id odio lobortis placerat. Mauris laoreet eu mi et semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at vehicula eros. Vestibulum ac ante at nunc faucibus maximus.`,
  },
  {
    id: '2',
    imageUrl: 'https://icapgroupgmbh.com/Quotely.jpg',
    name: 'Quotelly Wallpapers',
    text: 'Inspirierende Hintergrundbilder-App: Quotely. Große Auswahl an Zitaten, Hintergrundbildern von Stars und Naturfotos.',
    editionalText: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id justo quis orci aliquam porttitor nec ac orci. Vivamus ligula dui, aliquam in auctor eu, pulvinar at risus. Nulla facilisi. Morbi vitae magna at lorem rutrum tincidunt. Quisque in tempor justo. Cras risus metus, vehicula sit amet malesuada eget, convallis at lorem. Quisque vel nulla scelerisque, semper elit ultricies, euismod enim. Maecenas iaculis, ipsum vitae volutpat fringilla, neque massa elementum justo, at ultricies augue nunc ut quam. Phasellus vitae sagittis purus, vel sodales justo. Aliquam purus urna, luctus vel interdum in, luctus at sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus et nulla massa. Cras sollicitudin semper nisl, quis lobortis velit eleifend vitae. Morbi eget eros metus. Donec in orci quis orci facilisis lobortis viverra eget neque. Curabitur aliquam risus sem, in fringilla massa rhoncus vitae. Donec ex mi, ornare a convallis eu, maximus vel neque. Phasellus odio lacus, consectetur eget arcu eget, mattis auctor mi. Aliquam lacinia diam urna, scelerisque cursus felis convallis non. Duis mattis, neque sed consequat dignissim, est orci cursus ex, a bibendum metus lacus sit amet elit. Ut ultricies condimentum lorem, non blandit massa tempor ac. Nam pharetra, turpis eget rhoncus aliquam, quam augue faucibus justo, sit amet iaculis elit nulla ut massa. Vivamus luctus velit ac ipsum eleifend malesuada. Cras sodales finibus massa, at dapibus sem dapibus ac. Praesent a feugiat elit, et venenatis metus. Etiam accumsan, nibh vitae convallis finibus, magna est auctor sem, ut fermentum turpis nisi rutrum enim. Phasellus posuere felis et est ultricies, sed venenatis arcu luctus. Nam eu odio libero. In imperdiet eleifend nulla, ut tristique leo hendrerit ut. Pellentesque vel ex id odio lobortis placerat. Mauris laoreet eu mi et semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at vehicula eros. Vestibulum ac ante at nunc faucibus maximus.`,
  },
  {
    id: '3',
    imageUrl:
      'https://images.unsplash.com/photo-1548092372-0d1bd40894a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Ymx1ZSUyMGNvbXB1dGVyfGVufDB8fDB8fHww&w=1000&q=80',
    name: 'Lorem ipsum dolor',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur purus erat, dignissim in est vel, egestas suscipit tortor.',
    editionalText: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id justo quis orci aliquam porttitor nec ac orci. Vivamus ligula dui, aliquam in auctor eu, pulvinar at risus. Nulla facilisi. Morbi vitae magna at lorem rutrum tincidunt. Quisque in tempor justo. Cras risus metus, vehicula sit amet malesuada eget, convallis at lorem. Quisque vel nulla scelerisque, semper elit ultricies, euismod enim. Maecenas iaculis, ipsum vitae volutpat fringilla, neque massa elementum justo, at ultricies augue nunc ut quam. Phasellus vitae sagittis purus, vel sodales justo. Aliquam purus urna, luctus vel interdum in, luctus at sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus et nulla massa. Cras sollicitudin semper nisl, quis lobortis velit eleifend vitae. Morbi eget eros metus. Donec in orci quis orci facilisis lobortis viverra eget neque. Curabitur aliquam risus sem, in fringilla massa rhoncus vitae. Donec ex mi, ornare a convallis eu, maximus vel neque. Phasellus odio lacus, consectetur eget arcu eget, mattis auctor mi. Aliquam lacinia diam urna, scelerisque cursus felis convallis non. Duis mattis, neque sed consequat dignissim, est orci cursus ex, a bibendum metus lacus sit amet elit. Ut ultricies condimentum lorem, non blandit massa tempor ac. Nam pharetra, turpis eget rhoncus aliquam, quam augue faucibus justo, sit amet iaculis elit nulla ut massa. Vivamus luctus velit ac ipsum eleifend malesuada. Cras sodales finibus massa, at dapibus sem dapibus ac. Praesent a feugiat elit, et venenatis metus. Etiam accumsan, nibh vitae convallis finibus, magna est auctor sem, ut fermentum turpis nisi rutrum enim. Phasellus posuere felis et est ultricies, sed venenatis arcu luctus. Nam eu odio libero. In imperdiet eleifend nulla, ut tristique leo hendrerit ut. Pellentesque vel ex id odio lobortis placerat. Mauris laoreet eu mi et semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at vehicula eros. Vestibulum ac ante at nunc faucibus maximus.`,
  },
  {
    id: '4',
    imageUrl:
      'https://media.wired.com/photos/5f63ea43470e71528f4f8876/master/w_2560%2Cc_limit/Gear-Laptop-Monitor-159167665.jpg',
    name: 'Lorem ipsum dolor',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur purus erat, dignissim in est vel, egestas suscipit tortor.',
    editionalText: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id justo quis orci aliquam porttitor nec ac orci. Vivamus ligula dui, aliquam in auctor eu, pulvinar at risus. Nulla facilisi. Morbi vitae magna at lorem rutrum tincidunt. Quisque in tempor justo. Cras risus metus, vehicula sit amet malesuada eget, convallis at lorem. Quisque vel nulla scelerisque, semper elit ultricies, euismod enim. Maecenas iaculis, ipsum vitae volutpat fringilla, neque massa elementum justo, at ultricies augue nunc ut quam. Phasellus vitae sagittis purus, vel sodales justo. Aliquam purus urna, luctus vel interdum in, luctus at sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus et nulla massa. Cras sollicitudin semper nisl, quis lobortis velit eleifend vitae. Morbi eget eros metus. Donec in orci quis orci facilisis lobortis viverra eget neque. Curabitur aliquam risus sem, in fringilla massa rhoncus vitae. Donec ex mi, ornare a convallis eu, maximus vel neque. Phasellus odio lacus, consectetur eget arcu eget, mattis auctor mi. Aliquam lacinia diam urna, scelerisque cursus felis convallis non. Duis mattis, neque sed consequat dignissim, est orci cursus ex, a bibendum metus lacus sit amet elit. Ut ultricies condimentum lorem, non blandit massa tempor ac. Nam pharetra, turpis eget rhoncus aliquam, quam augue faucibus justo, sit amet iaculis elit nulla ut massa. Vivamus luctus velit ac ipsum eleifend malesuada. Cras sodales finibus massa, at dapibus sem dapibus ac. Praesent a feugiat elit, et venenatis metus. Etiam accumsan, nibh vitae convallis finibus, magna est auctor sem, ut fermentum turpis nisi rutrum enim. Phasellus posuere felis et est ultricies, sed venenatis arcu luctus. Nam eu odio libero. In imperdiet eleifend nulla, ut tristique leo hendrerit ut. Pellentesque vel ex id odio lobortis placerat. Mauris laoreet eu mi et semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at vehicula eros. Vestibulum ac ante at nunc faucibus maximus.`,
  },
  {
    id: '5',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCg2B6FWPk_lkz1FsP4df90C2sIHaAZy6a5A&usqp=CAU',
    name: 'Lorem ipsum dolor',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur purus erat, dignissim in est vel, egestas suscipit tortor.',
    editionalText: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id justo quis orci aliquam porttitor nec ac orci. Vivamus ligula dui, aliquam in auctor eu, pulvinar at risus. Nulla facilisi. Morbi vitae magna at lorem rutrum tincidunt. Quisque in tempor justo. Cras risus metus, vehicula sit amet malesuada eget, convallis at lorem. Quisque vel nulla scelerisque, semper elit ultricies, euismod enim. Maecenas iaculis, ipsum vitae volutpat fringilla, neque massa elementum justo, at ultricies augue nunc ut quam. Phasellus vitae sagittis purus, vel sodales justo. Aliquam purus urna, luctus vel interdum in, luctus at sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus et nulla massa. Cras sollicitudin semper nisl, quis lobortis velit eleifend vitae. Morbi eget eros metus. Donec in orci quis orci facilisis lobortis viverra eget neque. Curabitur aliquam risus sem, in fringilla massa rhoncus vitae. Donec ex mi, ornare a convallis eu, maximus vel neque. Phasellus odio lacus, consectetur eget arcu eget, mattis auctor mi. Aliquam lacinia diam urna, scelerisque cursus felis convallis non. Duis mattis, neque sed consequat dignissim, est orci cursus ex, a bibendum metus lacus sit amet elit. Ut ultricies condimentum lorem, non blandit massa tempor ac. Nam pharetra, turpis eget rhoncus aliquam, quam augue faucibus justo, sit amet iaculis elit nulla ut massa. Vivamus luctus velit ac ipsum eleifend malesuada. Cras sodales finibus massa, at dapibus sem dapibus ac. Praesent a feugiat elit, et venenatis metus. Etiam accumsan, nibh vitae convallis finibus, magna est auctor sem, ut fermentum turpis nisi rutrum enim. Phasellus posuere felis et est ultricies, sed venenatis arcu luctus. Nam eu odio libero. In imperdiet eleifend nulla, ut tristique leo hendrerit ut. Pellentesque vel ex id odio lobortis placerat. Mauris laoreet eu mi et semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at vehicula eros. Vestibulum ac ante at nunc faucibus maximus.`,
  },
  {
    id: '6',
    imageUrl: 'https://wallpaperaccess.com/full/4142125.jpg',
    name: 'Lorem ipsum dolor',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur purus erat, dignissim in est vel, egestas suscipit tortor.',
    editionalText: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id justo quis orci aliquam porttitor nec ac orci. Vivamus ligula dui, aliquam in auctor eu, pulvinar at risus. Nulla facilisi. Morbi vitae magna at lorem rutrum tincidunt. Quisque in tempor justo. Cras risus metus, vehicula sit amet malesuada eget, convallis at lorem. Quisque vel nulla scelerisque, semper elit ultricies, euismod enim. Maecenas iaculis, ipsum vitae volutpat fringilla, neque massa elementum justo, at ultricies augue nunc ut quam. Phasellus vitae sagittis purus, vel sodales justo. Aliquam purus urna, luctus vel interdum in, luctus at sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus et nulla massa. Cras sollicitudin semper nisl, quis lobortis velit eleifend vitae. Morbi eget eros metus. Donec in orci quis orci facilisis lobortis viverra eget neque. Curabitur aliquam risus sem, in fringilla massa rhoncus vitae. Donec ex mi, ornare a convallis eu, maximus vel neque. Phasellus odio lacus, consectetur eget arcu eget, mattis auctor mi. Aliquam lacinia diam urna, scelerisque cursus felis convallis non. Duis mattis, neque sed consequat dignissim, est orci cursus ex, a bibendum metus lacus sit amet elit. Ut ultricies condimentum lorem, non blandit massa tempor ac. Nam pharetra, turpis eget rhoncus aliquam, quam augue faucibus justo, sit amet iaculis elit nulla ut massa. Vivamus luctus velit ac ipsum eleifend malesuada. Cras sodales finibus massa, at dapibus sem dapibus ac. Praesent a feugiat elit, et venenatis metus. Etiam accumsan, nibh vitae convallis finibus, magna est auctor sem, ut fermentum turpis nisi rutrum enim. Phasellus posuere felis et est ultricies, sed venenatis arcu luctus. Nam eu odio libero. In imperdiet eleifend nulla, ut tristique leo hendrerit ut. Pellentesque vel ex id odio lobortis placerat. Mauris laoreet eu mi et semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at vehicula eros. Vestibulum ac ante at nunc faucibus maximus.`,
  },
];
